import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

import { ActiveContextProvider } from '@/context/ActiveContext'
import Header2 from "./components/Header2";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={`${inter.className} bg-[#07101f] relative`}>
        <ActiveContextProvider>
          <Header2 />
          <div className="flex flex-col w-full items-center justify-center">
            {children}
          </div>
          <Footer />
        </ActiveContextProvider>
      </body>
    </html>
  );
}